travis:
  secure:
    BINSTAR_TOKEN: r5bogptW0sXvsUsO59q3Ye8k0GbbBA4wjRangANZtA41mfjyXAuEIUUApLxhpj+7UtczNHTg9rtsQoI9F7M/c01fuc6X5NokrQ27f1bUHCYzp9gERwiljOhKj1vOKHbr6AoarW+u2nBl6y8OrumJD976EvKKWv+oNhn2NPwnPcMI0Q40rCwqoTKN5x9InqG65GZ1soJ4E3c/QfcgIS+hvhrwK1vvb7ooL2OAdu9UsbhHq9Jq5uo/SeeyvV3vwNxS4CJEVdsOkaWgdzDUeOWtXkJLV4Aievg3TR1NjwxdYKNHWy4u1e1GcMnRH2bPjDf1WwVMCRocI7KRZSKypYYL9N+yrEDHPTPRPh1OTh1urWdADN98oK0bIkel1XtdFYHmTuOVxpRADIfgoMIsuvSbIXeOdgUJUBTGrFkDLzLjLG8DOC29QYr7HXtDM60YjV/n2uH8K1qgQnOeKOzbz8l/1otlT5kmK7SNu7SlrvZ0PSsU5IzGmd9B45/G0hxIsmp9cT8EXOhTAao0Y2KuMfAlg5cjmToHJdxgXn+RqUKMG+MlNg6xHLVx+gbDFUzybiUEH0U7/1+TkKym47eDfcRdI66wCdfLbXvaF6/RSQfmwfGobxhY4Th2HjMGBMxhZ4njc+Gjoipeg1EAR44/h46QCpDq23uCVuW0J5BvwOC2+fc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
